### ISSUE TITLE
Assigning as process.env.NODE_ENV = deployTarget has no effect

### ISSUE THREAD

**Issue by belgoros** [kerimdzhanov/dotenv-flow#2]
I tried to use in an Ember app for deployment and it seems like it fails to read the right values.
Here is how it is defined in my `deploy.js`:
```
'use strict';
require('dotenv').config();
require('dotenv-flow').config();

module.exports = function(deployTarget) {
  process.env.NODE_ENV = deployTarget || 'development;

 if (deployTarget === 'staging') {
    console.log('NODE-ENV: ' + process.env.NODE_ENV);
    ENV.s3 = {
      accessKeyId: process.env.AWS_ACCESS_KEY,
      secretAccessKey: process.env.AWS_SECRET_KEY,
      bucket: 'XXXX',
      region: 'eu-west-1'
    };

     ENV['s3-index'] = {
      accessKeyId: process.env.AWS_ACCESS_KEY,
      secretAccessKey: process.env.AWS_SECRET_KEY,
      bucket: 'XXXX',
      region: 'eu-west-1'
    };
  }
}
```
It fails to deploy with errors:
```
+- didFail
CredentialsError: Missing credentials in config
CredentialsError: Missing credentials in config
    at ClientRequest.<anonymous> (/Users/XXX/projects/XXX/XXXX/node_modules/aws-sdk/lib/http/node.js:83:34)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at ClientRequest.emit (events.js:208:7)
    at Socket.emitTimeout (_http_client.js:706:34)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:410:8)
    at ontimeout (timers.js:498:11)|
Pipeline aborted
```
I defined 2 separate files in the project root:
- `.env`
- `.env.staging``

What's wrong with that? Can't I assign a value to `process.env.NODE_ENV = ...`? 
Thank you.

**Comment by belgoros** [comment]
Yep, it worked for me 👍. Thanks a lot ! 👏 
I also removed completely previously installed `dotenv` package with `yarn remove dotenv`, rigth ?

**Comment by kerimdzhanov** [comment]
Yep! That's correct.

**Comment by belgoros** [comment]
Thanks again (спасибо) !
